sudo: required
language: python
services:
  - docker
before_install:
  - tar -cvf files.tar *
  - docker pull proycon/lamachine
  - docker run -t -d --name lamachine proycon/lamachine
  - docker cp files.tar lamachine:/tmp/
  - docker exec lamachine tar -xf /tmp/files.tar -C /tmp
install:
  - docker exec lamachine pip install -r /tmp/requirements.txt
  - docker exec lamachine pip install mypy
script:
  - docker exec lamachine python -m mypy **/*.py --ignore-missing-imports
  - docker exec lamachine python -m unittest
  - docker stop lamachine
