sudo: required
language: python
python:
  - 3.6
install:
  - apt install libfolia-dev libxml2-dev
  - pip install -r /tmp/requirements.txt
script:
  - python -m unittest
  - pip install mypy
  - mypy **/*.py --ignore-missing-imports
